<?php

/**
 * Implements hook_theme().
 */
function makerspace_member_year_review_theme($existing, $type, $theme, $path) {
  return [
    'member_year_review' => [
      'variables' => [
        'user_name' => NULL,
        'first_name' => NULL,
        'user_id' => NULL,
        'year' => NULL,
        'stats' => [],
        'profile' => [],
        'deltas' => [],
        'ranks' => [],
        'active_members_total' => NULL,
        'community_stats' => [],
        'community_full_report' => [],
        'fun_award' => NULL,
        'survey_form' => NULL,
        'survey_link_url' => NULL,
      ],
    ],
  ];
}
